# Generated by Django 2.0.13 on 2019-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detailed_text',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
